data:
    dataset: "Prostate"
    train_dataroot: "/path/to/your/DATASET/Prostate_resize"
    sample_dataroot: "/path/to/your/DATASET/Prostate_resize"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8

model:
    type: "sg"
    in_channels: 6
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 6
    n_epochs: 20000
    n_iters: 5000000
    snapshot_freq: 250417
    validation_freq: 5000000000

sampling:
    batch_size: 8
    ckpt_id: [2504170]
    last_only: True

sampling_inter:
    batch_size: 59
    last_only: True

sampling_fid:
    batch_size: 16
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
